# site settings
title: ST5K DESIGN
subtitle: 
email: st5kdesigns@gmail.com
description: Portfolio Site for ST5K DESIGN
baseurl: "/" 
url: "https://st5kdesign.github.io"
author:
street_address: 
city: Galena
state: OH
zip_code: 43021
country: United States of America
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
